name: GridCopy
favicon: null
layout_spectrum: 0.24929
typography_spectrum: 0.29158
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#151515'
    - '#313131'
    - '#c8c8c8'
    - '#696969'
    - '#ffffff'
  brandStrength: 0.125
  lightness: 0.1875
  saturation: 0.8724023455288261
  rhythmicContrast: 0.23697320045903325
purpose: []
